"""Fill the lab's GenScript gene-synthesis quote template with a built
construct's insert sequence, so ordering it doesn't mean retyping the DNA
by hand into someone else's spreadsheet.

The template ships at data/templates/gene_synthesis_quote_template.xlsx: the
vendor's own form (headers, instructions, dropdown lists, one example row),
with a prior project's real order rows cleared out. We only ever fill in
the first still-empty data row -- nothing else in the sheet is touched.
"""

from __future__ import annotations

import io
from datetime import date

import openpyxl

from .codon_usage import DATA_DIR

TEMPLATE_PATH = DATA_DIR / "templates" / "gene_synthesis_quote_template.xlsx"
SHEET_NAME = "Gene Synthesis"
FIRST_DATA_ROW = 20  # row 19 is the vendor's own example row; data starts here
GENE_NAME_COL = 2    # B
LAST_DATA_ROW = 113  # matches the template's pre-numbered "No." column

# GenScript's Host Expression Organism cell is a dropdown (data validation
# list); only pick a value from that list, or "Other" plus a note, never a
# host name the vendor's form doesn't offer.
HOST_TO_GENSCRIPT = {
    "e_coli_bl21_de3": "Escherichia coli",
    "e_coli_k12": "Escherichia coli",
    "s_cerevisiae": "Saccharomyces cerevisiae(gbpln)",
    "human": "Human",
    "p_pastoris": "Pichia pastoris",
}


class GeneOrderError(ValueError):
    pass


def fill_order_template(gene_name: str, insert: str, host_title: str, host_id: str, backbone: str,
                         ready_to_order: dict) -> bytes:
    """Return the .xlsx template's bytes with one new row filled in.

    insert: the promoter+RBS+CDS+terminator DNA to synthesize (not the whole
    plasmid -- the backbone is a vector the lab already has, named in the
    Cloning Vector column, not something GenScript needs to build).
    """
    insert = "".join(insert.split()).upper()
    if not insert or set(insert) - set("ACGT"):
        raise GeneOrderError("insert must be DNA (A, C, G, T only).")
    if not TEMPLATE_PATH.exists():
        raise GeneOrderError("Gene order template is missing from the server.")

    wb = openpyxl.load_workbook(TEMPLATE_PATH)
    ws = wb[SHEET_NAME]

    row = None
    for r in range(FIRST_DATA_ROW, LAST_DATA_ROW + 1):
        if ws.cell(row=r, column=GENE_NAME_COL).value in (None, ""):
            row = r
            break
    if row is None:
        raise GeneOrderError("The gene order template has no free rows left.")

    genscript_host = HOST_TO_GENSCRIPT.get(host_id, "Other")
    comment = f"Generated by Plasmid Design Assistant, {date.today().isoformat()}."
    if genscript_host == "Other":
        comment += f" Host: {host_title} (not in GenScript's organism list -- please confirm handling)."
    comment += " Ready to order: " + ("yes." if ready_to_order.get("ok") else
                                       "no -- " + " ".join(ready_to_order.get("blockers", [])))

    ws.cell(row=row, column=2).value = gene_name           # B  Gene Name
    ws.cell(row=row, column=4).value = insert               # D  Sequence
    ws.cell(row=row, column=7).value = len(insert)          # G  Length [Bases]
    ws.cell(row=row, column=8).value = "No"                 # H  Codon Optimization (done already, in-app)
    ws.cell(row=row, column=9).value = genscript_host       # I  Host Expression Organism
    ws.cell(row=row, column=13).value = "Included in CDS"   # M  Stop Codon
    ws.cell(row=row, column=14).value = backbone            # N  Cloning Vector
    ws.cell(row=row, column=17).value = comment             # Q  Comment

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
